name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Ctarget-cpu=x86-64-v3 -Cincremental=build -Clink-arg=-fuse-ld=lld -Cstrip=symbols
    steps:
      - uses: actions/checkout@v3

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - name: setup cache
        uses: Swatinem/rust-cache@v2
        with:
          env-vars: CARGO CC CFLAGS CXX CMAKE RUST RUSTFLAGS

      - name: build
        run: cargo build --release --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: selfserv-win64
          path: ./target/release/selfservd
            ./target/release/selfctl

      - name: test
        run: cargo test --verbose --all-features

  build-windows:
    runs-on: windows-latest
    env:
      RUSTFLAGS: -Ctarget-cpu=x86-64-v3 -Cincremental=build -Clink-arg=-fuse-ld=lld -Cstrip=symbols
    steps:
      - uses: actions/checkout@v3

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - name: setup cache
        uses: Swatinem/rust-cache@v2
        with:
          env-vars: CARGO CC CFLAGS CXX CMAKE RUST RUSTFLAGS

      - name: build
        run: cargo build --release --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: selfserv-win64
          path: ./target/release/selfservd.exe
            ./target/release/selfctl.exe

      - name: test
        run: cargo test --verbose --all-features

  build-macos:
    runs-on: macos-latest
    env:
      RUSTFLAGS: -Ctarget-cpu=x86-64-v3 -Cincremental=build -Cstrip=symbols
    steps:
      - uses: actions/checkout@v3

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - name: setup cache
        uses: Swatinem/rust-cache@v2
        with:
          env-vars: CARGO CC CFLAGS CXX CMAKE RUST RUSTFLAGS

      - name: build
        run: cargo build --release --verbose

      - name: test
        run: cargo test --verbose --all-features
